- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: 
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: mbot
        spec:
          serviceName: mbot
          template:
            metadata:
              labels:
                app: mbot
            spec:
              containers:
              - image: "{{ image }}"
                name: mbot
                env:
                - name: MYSQL_HOST
                  value: mysql
                - name: MYSQL_PORT
                  value: "3306"
                - name: REDIS_HOST
                  value: redis-1655768572-master-0
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  value: "a8ElD0aWae"
                volumeMounts:
                - name: mbot-persistent-storage
                  mountPath: /mbot/img_cache
              volumes:
              - name: mbot-persistent-storage
                persistentVolumeClaim:
                  claimName: nfs-discordbot-pvc
          selector:
            matchLabels:
              app: mbot
      validate_certs: no
      namespace: discordbots
