- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('file', 'kubernetes.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
