spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:""}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/mbot?createDatabaseIfNotExist=true
    username: root
    password: JhyjCDHaV2
    hikari:
      max-lifetime: 580000

tokens:
  file: ${TOKEN_LOCATION:tokens.properties}
web3j:
  client-address: https://arb1.arbitrum.io/rpc
